# automation to add issues to tracker board (test)
# dev: DC

name: Add issues/PRs to Org Project

on:
  issues:
    types: [opened, reopened, transferred, labeled]
  pull_request:
    types: [opened, reopened, ready_for_review, labeled]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add item to org project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/cantinilab/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
      # 2) (ISSUES) make/update  label 'repo:<repo>'
      - name: Ensure repo label exists (issues)
        if: github.event_name == 'issues'
        uses: peter-evans/create-or-update-label@v4
        with:
          name: repo:${{ github.event.repository.name }}
          color: 666666
          description: Issue origin repository

      # 3) (ISSUES) apply the label 'repo:<repo>' to the issue
      - name: Add repo label to issue
        if: github.event_name == 'issues'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: repo:${{ github.event.repository.name }}
