name: Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage pre-commit
          # se NON è un package Python, commenta la riga seguente
          pip install . || true

      - name: Run pre-commit (non-blocking)
        run: |
          pre-commit install
          pre-commit run --all-files || true

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          coverage run -m pytest || true
          coverage xml || true

      - name: Upload Coverage to Codecov (if token present)
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
